/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { VerificationInformation } from "./VerificationInformation";
import { VerificationInformationCountArgs } from "./VerificationInformationCountArgs";
import { VerificationInformationFindManyArgs } from "./VerificationInformationFindManyArgs";
import { VerificationInformationFindUniqueArgs } from "./VerificationInformationFindUniqueArgs";
import { CreateVerificationInformationArgs } from "./CreateVerificationInformationArgs";
import { UpdateVerificationInformationArgs } from "./UpdateVerificationInformationArgs";
import { DeleteVerificationInformationArgs } from "./DeleteVerificationInformationArgs";
import { User } from "../../user/base/User";
import { VerificationInformationService } from "../verificationInformation.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => VerificationInformation)
export class VerificationInformationResolverBase {
  constructor(
    protected readonly service: VerificationInformationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "VerificationInformation",
    action: "read",
    possession: "any",
  })
  async _verificationInformationsMeta(
    @graphql.Args() args: VerificationInformationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [VerificationInformation])
  @nestAccessControl.UseRoles({
    resource: "VerificationInformation",
    action: "read",
    possession: "any",
  })
  async verificationInformations(
    @graphql.Args() args: VerificationInformationFindManyArgs
  ): Promise<VerificationInformation[]> {
    return this.service.verificationInformations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => VerificationInformation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "VerificationInformation",
    action: "read",
    possession: "own",
  })
  async verificationInformation(
    @graphql.Args() args: VerificationInformationFindUniqueArgs
  ): Promise<VerificationInformation | null> {
    const result = await this.service.verificationInformation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => VerificationInformation)
  @nestAccessControl.UseRoles({
    resource: "VerificationInformation",
    action: "create",
    possession: "any",
  })
  async createVerificationInformation(
    @graphql.Args() args: CreateVerificationInformationArgs
  ): Promise<VerificationInformation> {
    return await this.service.createVerificationInformation({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => VerificationInformation)
  @nestAccessControl.UseRoles({
    resource: "VerificationInformation",
    action: "update",
    possession: "any",
  })
  async updateVerificationInformation(
    @graphql.Args() args: UpdateVerificationInformationArgs
  ): Promise<VerificationInformation | null> {
    try {
      return await this.service.updateVerificationInformation({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => VerificationInformation)
  @nestAccessControl.UseRoles({
    resource: "VerificationInformation",
    action: "delete",
    possession: "any",
  })
  async deleteVerificationInformation(
    @graphql.Args() args: DeleteVerificationInformationArgs
  ): Promise<VerificationInformation | null> {
    try {
      return await this.service.deleteVerificationInformation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(
    @graphql.Parent() parent: VerificationInformation
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
