/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VerificationInformationService } from "../verificationInformation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VerificationInformationCreateInput } from "./VerificationInformationCreateInput";
import { VerificationInformation } from "./VerificationInformation";
import { VerificationInformationFindManyArgs } from "./VerificationInformationFindManyArgs";
import { VerificationInformationWhereUniqueInput } from "./VerificationInformationWhereUniqueInput";
import { VerificationInformationUpdateInput } from "./VerificationInformationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VerificationInformationControllerBase {
  constructor(
    protected readonly service: VerificationInformationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VerificationInformation })
  @nestAccessControl.UseRoles({
    resource: "VerificationInformation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: VerificationInformationCreateInput,
  })
  async createVerificationInformation(
    @common.Body() data: VerificationInformationCreateInput
  ): Promise<VerificationInformation> {
    return await this.service.createVerificationInformation({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        cacDocument: true,
        countryOfIncorporation: true,
        createdAt: true,
        currentOccupation: true,
        dateOfExpiry: true,
        dateOfIssue: true,
        id: true,
        identificationDocument: true,
        identificationNumber: true,
        organisationAddress: true,
        organisationName: true,
        placeOfIssue: true,
        position: true,
        registrationNumber: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [VerificationInformation] })
  @ApiNestedQuery(VerificationInformationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "VerificationInformation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async verificationInformations(
    @common.Req() request: Request
  ): Promise<VerificationInformation[]> {
    const args = plainToClass(
      VerificationInformationFindManyArgs,
      request.query
    );
    return this.service.verificationInformations({
      ...args,
      select: {
        cacDocument: true,
        countryOfIncorporation: true,
        createdAt: true,
        currentOccupation: true,
        dateOfExpiry: true,
        dateOfIssue: true,
        id: true,
        identificationDocument: true,
        identificationNumber: true,
        organisationAddress: true,
        organisationName: true,
        placeOfIssue: true,
        position: true,
        registrationNumber: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VerificationInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VerificationInformation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async verificationInformation(
    @common.Param() params: VerificationInformationWhereUniqueInput
  ): Promise<VerificationInformation | null> {
    const result = await this.service.verificationInformation({
      where: params,
      select: {
        cacDocument: true,
        countryOfIncorporation: true,
        createdAt: true,
        currentOccupation: true,
        dateOfExpiry: true,
        dateOfIssue: true,
        id: true,
        identificationDocument: true,
        identificationNumber: true,
        organisationAddress: true,
        organisationName: true,
        placeOfIssue: true,
        position: true,
        registrationNumber: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VerificationInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VerificationInformation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: VerificationInformationUpdateInput,
  })
  async updateVerificationInformation(
    @common.Param() params: VerificationInformationWhereUniqueInput,
    @common.Body() data: VerificationInformationUpdateInput
  ): Promise<VerificationInformation | null> {
    try {
      return await this.service.updateVerificationInformation({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          cacDocument: true,
          countryOfIncorporation: true,
          createdAt: true,
          currentOccupation: true,
          dateOfExpiry: true,
          dateOfIssue: true,
          id: true,
          identificationDocument: true,
          identificationNumber: true,
          organisationAddress: true,
          organisationName: true,
          placeOfIssue: true,
          position: true,
          registrationNumber: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VerificationInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VerificationInformation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVerificationInformation(
    @common.Param() params: VerificationInformationWhereUniqueInput
  ): Promise<VerificationInformation | null> {
    try {
      return await this.service.deleteVerificationInformation({
        where: params,
        select: {
          cacDocument: true,
          countryOfIncorporation: true,
          createdAt: true,
          currentOccupation: true,
          dateOfExpiry: true,
          dateOfIssue: true,
          id: true,
          identificationDocument: true,
          identificationNumber: true,
          organisationAddress: true,
          organisationName: true,
          placeOfIssue: true,
          position: true,
          registrationNumber: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
