/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  VerificationInformation as PrismaVerificationInformation,
  User as PrismaUser,
} from "@prisma/client";

export class VerificationInformationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.VerificationInformationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.verificationInformation.count(args);
  }

  async verificationInformations(
    args: Prisma.VerificationInformationFindManyArgs
  ): Promise<PrismaVerificationInformation[]> {
    return this.prisma.verificationInformation.findMany(args);
  }
  async verificationInformation(
    args: Prisma.VerificationInformationFindUniqueArgs
  ): Promise<PrismaVerificationInformation | null> {
    return this.prisma.verificationInformation.findUnique(args);
  }
  async createVerificationInformation(
    args: Prisma.VerificationInformationCreateArgs
  ): Promise<PrismaVerificationInformation> {
    return this.prisma.verificationInformation.create(args);
  }
  async updateVerificationInformation(
    args: Prisma.VerificationInformationUpdateArgs
  ): Promise<PrismaVerificationInformation> {
    return this.prisma.verificationInformation.update(args);
  }
  async deleteVerificationInformation(
    args: Prisma.VerificationInformationDeleteArgs
  ): Promise<PrismaVerificationInformation> {
    return this.prisma.verificationInformation.delete(args);
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.verificationInformation
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
