/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ContactInformation } from "./ContactInformation";
import { ContactInformationCountArgs } from "./ContactInformationCountArgs";
import { ContactInformationFindManyArgs } from "./ContactInformationFindManyArgs";
import { ContactInformationFindUniqueArgs } from "./ContactInformationFindUniqueArgs";
import { CreateContactInformationArgs } from "./CreateContactInformationArgs";
import { UpdateContactInformationArgs } from "./UpdateContactInformationArgs";
import { DeleteContactInformationArgs } from "./DeleteContactInformationArgs";
import { User } from "../../user/base/User";
import { ContactInformationService } from "../contactInformation.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ContactInformation)
export class ContactInformationResolverBase {
  constructor(
    protected readonly service: ContactInformationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ContactInformation",
    action: "read",
    possession: "any",
  })
  async _contactInformationsMeta(
    @graphql.Args() args: ContactInformationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ContactInformation])
  @nestAccessControl.UseRoles({
    resource: "ContactInformation",
    action: "read",
    possession: "any",
  })
  async contactInformations(
    @graphql.Args() args: ContactInformationFindManyArgs
  ): Promise<ContactInformation[]> {
    return this.service.contactInformations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ContactInformation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ContactInformation",
    action: "read",
    possession: "own",
  })
  async contactInformation(
    @graphql.Args() args: ContactInformationFindUniqueArgs
  ): Promise<ContactInformation | null> {
    const result = await this.service.contactInformation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ContactInformation)
  @nestAccessControl.UseRoles({
    resource: "ContactInformation",
    action: "create",
    possession: "any",
  })
  async createContactInformation(
    @graphql.Args() args: CreateContactInformationArgs
  ): Promise<ContactInformation> {
    return await this.service.createContactInformation({
      ...args,
      data: {
        ...args.data,

        users: args.data.users
          ? {
              connect: args.data.users,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ContactInformation)
  @nestAccessControl.UseRoles({
    resource: "ContactInformation",
    action: "update",
    possession: "any",
  })
  async updateContactInformation(
    @graphql.Args() args: UpdateContactInformationArgs
  ): Promise<ContactInformation | null> {
    try {
      return await this.service.updateContactInformation({
        ...args,
        data: {
          ...args.data,

          users: args.data.users
            ? {
                connect: args.data.users,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ContactInformation)
  @nestAccessControl.UseRoles({
    resource: "ContactInformation",
    action: "delete",
    possession: "any",
  })
  async deleteContactInformation(
    @graphql.Args() args: DeleteContactInformationArgs
  ): Promise<ContactInformation | null> {
    try {
      return await this.service.deleteContactInformation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "users",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUsers(
    @graphql.Parent() parent: ContactInformation
  ): Promise<User | null> {
    const result = await this.service.getUsers(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
