/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ContactInformationService } from "../contactInformation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ContactInformationCreateInput } from "./ContactInformationCreateInput";
import { ContactInformation } from "./ContactInformation";
import { ContactInformationFindManyArgs } from "./ContactInformationFindManyArgs";
import { ContactInformationWhereUniqueInput } from "./ContactInformationWhereUniqueInput";
import { ContactInformationUpdateInput } from "./ContactInformationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ContactInformationControllerBase {
  constructor(
    protected readonly service: ContactInformationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ContactInformation })
  @nestAccessControl.UseRoles({
    resource: "ContactInformation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ContactInformationCreateInput,
  })
  async createContactInformation(
    @common.Body() data: ContactInformationCreateInput
  ): Promise<ContactInformation> {
    return await this.service.createContactInformation({
      data: {
        ...data,

        users: data.users
          ? {
              connect: data.users,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        lga: true,
        lgaOfResidence: true,
        phoneNumber: true,
        residentialAddress: true,
        stateOfOrigin: true,
        stateOfResidence: true,
        updatedAt: true,

        users: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ContactInformation] })
  @ApiNestedQuery(ContactInformationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ContactInformation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async contactInformations(
    @common.Req() request: Request
  ): Promise<ContactInformation[]> {
    const args = plainToClass(ContactInformationFindManyArgs, request.query);
    return this.service.contactInformations({
      ...args,
      select: {
        createdAt: true,
        id: true,
        lga: true,
        lgaOfResidence: true,
        phoneNumber: true,
        residentialAddress: true,
        stateOfOrigin: true,
        stateOfResidence: true,
        updatedAt: true,

        users: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ContactInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ContactInformation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async contactInformation(
    @common.Param() params: ContactInformationWhereUniqueInput
  ): Promise<ContactInformation | null> {
    const result = await this.service.contactInformation({
      where: params,
      select: {
        createdAt: true,
        id: true,
        lga: true,
        lgaOfResidence: true,
        phoneNumber: true,
        residentialAddress: true,
        stateOfOrigin: true,
        stateOfResidence: true,
        updatedAt: true,

        users: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ContactInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ContactInformation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ContactInformationUpdateInput,
  })
  async updateContactInformation(
    @common.Param() params: ContactInformationWhereUniqueInput,
    @common.Body() data: ContactInformationUpdateInput
  ): Promise<ContactInformation | null> {
    try {
      return await this.service.updateContactInformation({
        where: params,
        data: {
          ...data,

          users: data.users
            ? {
                connect: data.users,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          lga: true,
          lgaOfResidence: true,
          phoneNumber: true,
          residentialAddress: true,
          stateOfOrigin: true,
          stateOfResidence: true,
          updatedAt: true,

          users: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ContactInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ContactInformation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteContactInformation(
    @common.Param() params: ContactInformationWhereUniqueInput
  ): Promise<ContactInformation | null> {
    try {
      return await this.service.deleteContactInformation({
        where: params,
        select: {
          createdAt: true,
          id: true,
          lga: true,
          lgaOfResidence: true,
          phoneNumber: true,
          residentialAddress: true,
          stateOfOrigin: true,
          stateOfResidence: true,
          updatedAt: true,

          users: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
