/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ContactInformation as PrismaContactInformation,
  User as PrismaUser,
} from "@prisma/client";

export class ContactInformationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ContactInformationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.contactInformation.count(args);
  }

  async contactInformations(
    args: Prisma.ContactInformationFindManyArgs
  ): Promise<PrismaContactInformation[]> {
    return this.prisma.contactInformation.findMany(args);
  }
  async contactInformation(
    args: Prisma.ContactInformationFindUniqueArgs
  ): Promise<PrismaContactInformation | null> {
    return this.prisma.contactInformation.findUnique(args);
  }
  async createContactInformation(
    args: Prisma.ContactInformationCreateArgs
  ): Promise<PrismaContactInformation> {
    return this.prisma.contactInformation.create(args);
  }
  async updateContactInformation(
    args: Prisma.ContactInformationUpdateArgs
  ): Promise<PrismaContactInformation> {
    return this.prisma.contactInformation.update(args);
  }
  async deleteContactInformation(
    args: Prisma.ContactInformationDeleteArgs
  ): Promise<PrismaContactInformation> {
    return this.prisma.contactInformation.delete(args);
  }

  async getUsers(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.contactInformation
      .findUnique({
        where: { id: parentId },
      })
      .users();
  }
}
