/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ContactInformationWhereUniqueInput } from "../../contactInformation/base/ContactInformationWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { PersonalInformationWhereUniqueInput } from "../../personalInformation/base/PersonalInformationWhereUniqueInput";
import { VerificationInformationWhereUniqueInput } from "../../verificationInformation/base/VerificationInformationWhereUniqueInput";

@InputType()
class UserWhereInput {
  @ApiProperty({
    required: false,
    type: () => ContactInformationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ContactInformationWhereUniqueInput)
  @IsOptional()
  @Field(() => ContactInformationWhereUniqueInput, {
    nullable: true,
  })
  contactInformation?: ContactInformationWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  email?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  firstName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  lastName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PersonalInformationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PersonalInformationWhereUniqueInput)
  @IsOptional()
  @Field(() => PersonalInformationWhereUniqueInput, {
    nullable: true,
  })
  personalInformation?: PersonalInformationWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  signUpCredentials?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  username?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => VerificationInformationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => VerificationInformationWhereUniqueInput)
  @IsOptional()
  @Field(() => VerificationInformationWhereUniqueInput, {
    nullable: true,
  })
  verificationInformation?: VerificationInformationWhereUniqueInput;
}

export { UserWhereInput as UserWhereInput };
