/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PersonalInformationService } from "../personalInformation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PersonalInformationCreateInput } from "./PersonalInformationCreateInput";
import { PersonalInformation } from "./PersonalInformation";
import { PersonalInformationFindManyArgs } from "./PersonalInformationFindManyArgs";
import { PersonalInformationWhereUniqueInput } from "./PersonalInformationWhereUniqueInput";
import { PersonalInformationUpdateInput } from "./PersonalInformationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PersonalInformationControllerBase {
  constructor(
    protected readonly service: PersonalInformationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PersonalInformation })
  @nestAccessControl.UseRoles({
    resource: "PersonalInformation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: PersonalInformationCreateInput,
  })
  async createPersonalInformation(
    @common.Body() data: PersonalInformationCreateInput
  ): Promise<PersonalInformation> {
    return await this.service.createPersonalInformation({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        dateOfBirth: true,
        firstName: true,
        gender: true,
        id: true,
        lastName: true,
        middleName: true,
        nin: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PersonalInformation] })
  @ApiNestedQuery(PersonalInformationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PersonalInformation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async personalInformations(
    @common.Req() request: Request
  ): Promise<PersonalInformation[]> {
    const args = plainToClass(PersonalInformationFindManyArgs, request.query);
    return this.service.personalInformations({
      ...args,
      select: {
        createdAt: true,
        dateOfBirth: true,
        firstName: true,
        gender: true,
        id: true,
        lastName: true,
        middleName: true,
        nin: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PersonalInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PersonalInformation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async personalInformation(
    @common.Param() params: PersonalInformationWhereUniqueInput
  ): Promise<PersonalInformation | null> {
    const result = await this.service.personalInformation({
      where: params,
      select: {
        createdAt: true,
        dateOfBirth: true,
        firstName: true,
        gender: true,
        id: true,
        lastName: true,
        middleName: true,
        nin: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PersonalInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PersonalInformation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: PersonalInformationUpdateInput,
  })
  async updatePersonalInformation(
    @common.Param() params: PersonalInformationWhereUniqueInput,
    @common.Body() data: PersonalInformationUpdateInput
  ): Promise<PersonalInformation | null> {
    try {
      return await this.service.updatePersonalInformation({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          dateOfBirth: true,
          firstName: true,
          gender: true,
          id: true,
          lastName: true,
          middleName: true,
          nin: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PersonalInformation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PersonalInformation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePersonalInformation(
    @common.Param() params: PersonalInformationWhereUniqueInput
  ): Promise<PersonalInformation | null> {
    try {
      return await this.service.deletePersonalInformation({
        where: params,
        select: {
          createdAt: true,
          dateOfBirth: true,
          firstName: true,
          gender: true,
          id: true,
          lastName: true,
          middleName: true,
          nin: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
