/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  PersonalInformation as PrismaPersonalInformation,
  User as PrismaUser,
} from "@prisma/client";

export class PersonalInformationServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PersonalInformationCountArgs, "select">
  ): Promise<number> {
    return this.prisma.personalInformation.count(args);
  }

  async personalInformations(
    args: Prisma.PersonalInformationFindManyArgs
  ): Promise<PrismaPersonalInformation[]> {
    return this.prisma.personalInformation.findMany(args);
  }
  async personalInformation(
    args: Prisma.PersonalInformationFindUniqueArgs
  ): Promise<PrismaPersonalInformation | null> {
    return this.prisma.personalInformation.findUnique(args);
  }
  async createPersonalInformation(
    args: Prisma.PersonalInformationCreateArgs
  ): Promise<PrismaPersonalInformation> {
    return this.prisma.personalInformation.create(args);
  }
  async updatePersonalInformation(
    args: Prisma.PersonalInformationUpdateArgs
  ): Promise<PrismaPersonalInformation> {
    return this.prisma.personalInformation.update(args);
  }
  async deletePersonalInformation(
    args: Prisma.PersonalInformationDeleteArgs
  ): Promise<PrismaPersonalInformation> {
    return this.prisma.personalInformation.delete(args);
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.personalInformation
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
