/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { PersonalInformation } from "./PersonalInformation";
import { PersonalInformationCountArgs } from "./PersonalInformationCountArgs";
import { PersonalInformationFindManyArgs } from "./PersonalInformationFindManyArgs";
import { PersonalInformationFindUniqueArgs } from "./PersonalInformationFindUniqueArgs";
import { CreatePersonalInformationArgs } from "./CreatePersonalInformationArgs";
import { UpdatePersonalInformationArgs } from "./UpdatePersonalInformationArgs";
import { DeletePersonalInformationArgs } from "./DeletePersonalInformationArgs";
import { User } from "../../user/base/User";
import { PersonalInformationService } from "../personalInformation.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PersonalInformation)
export class PersonalInformationResolverBase {
  constructor(
    protected readonly service: PersonalInformationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PersonalInformation",
    action: "read",
    possession: "any",
  })
  async _personalInformationsMeta(
    @graphql.Args() args: PersonalInformationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PersonalInformation])
  @nestAccessControl.UseRoles({
    resource: "PersonalInformation",
    action: "read",
    possession: "any",
  })
  async personalInformations(
    @graphql.Args() args: PersonalInformationFindManyArgs
  ): Promise<PersonalInformation[]> {
    return this.service.personalInformations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PersonalInformation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PersonalInformation",
    action: "read",
    possession: "own",
  })
  async personalInformation(
    @graphql.Args() args: PersonalInformationFindUniqueArgs
  ): Promise<PersonalInformation | null> {
    const result = await this.service.personalInformation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PersonalInformation)
  @nestAccessControl.UseRoles({
    resource: "PersonalInformation",
    action: "create",
    possession: "any",
  })
  async createPersonalInformation(
    @graphql.Args() args: CreatePersonalInformationArgs
  ): Promise<PersonalInformation> {
    return await this.service.createPersonalInformation({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PersonalInformation)
  @nestAccessControl.UseRoles({
    resource: "PersonalInformation",
    action: "update",
    possession: "any",
  })
  async updatePersonalInformation(
    @graphql.Args() args: UpdatePersonalInformationArgs
  ): Promise<PersonalInformation | null> {
    try {
      return await this.service.updatePersonalInformation({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PersonalInformation)
  @nestAccessControl.UseRoles({
    resource: "PersonalInformation",
    action: "delete",
    possession: "any",
  })
  async deletePersonalInformation(
    @graphql.Args() args: DeletePersonalInformationArgs
  ): Promise<PersonalInformation | null> {
    try {
      return await this.service.deletePersonalInformation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(
    @graphql.Parent() parent: PersonalInformation
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
